/* CLAUSULA DELETE */

/* VAI DETELA A TABELA INTEIRA */
DELETE FROM CLIENTE;

/* CONTANDO A QUANTIDADE DE REGISTROS DA TABELA - É IMPORTANTE */
SELECT COUNT(*) FROM CLIENTE;

/* CONTANDO OS REGISTRO USANDO O WHERE PARA FAZER A SELEÇÃO DO REGISTRO QUE EU QUERO CONTAR */
SELECT COUNT(*) FROM CLIENTE -- TOTAL 6
WHERE NOME = 'ANA';

/* DELETANDO O REGISTRO DA TABELA - SEMPRE USAR O WHERE 
JUNTO COM O DELETE PARA DELETAR APENAS O REGISTRO SELECIONADO  */
DELETE FROM CLIENTE -- TOTAL DELETADO 1
WHERE NOME = 'ANA';

/* CONTANDO NOVAMENTE A QUANTIDADE DE REGISTROS PARA VER SE DEU CERTO E DEU */
SELECT COUNT(*) FROM CLIENTE; -- TOTAL 5

SELECT * FROM CLIENTE;

/* INSERINDO NOVOS DADOS NA TABELA */
INSERT INTO CLIENTE VALUES('CARLA', 'F', 'C.LOPES@OUL.COM', 45638854, '4575-0048', 'RUA COPPER LEAF - WILLIAMBURG - KITCHEBER');

/* DELETANDO UM REGISTRO QUE TEM NOMES IGUAIS MAS NÃO SÃO A MESMA PESSOA */

SELECT * FROM CLIENTE -- ME CERTIFICANDO QUE VOU DELETAE O REGISTRO CORRETO 
WHERE NOME = 'CARLA'
OR EMAIL = 'C.LOPES@OUL.COM'; -- O OR TRAZ TODO MUNDO COM PELO MENOS UMA DAS DUAS CONDIÇÕES


SELECT * FROM CLIENTE -- ME CERTIFICANDO QUE VOU DELETAE O REGISTRO CORRETO 
WHERE NOME = 'CARLA'
AND EMAIL = 'C.LOPES@OUL.COM'; -- O AND TRAZ APENAS O REGISTRO QUE SATISFAÇA AS DUAS CONDIÇÕES

DELETE FROM CLIENTE
WHERE NOME = 'CARLA' 
AND EMAIL = 'C.LOPES@OUL.COM';

