/* Modelagem Básica */

/* ENTIDADE = TABELA 
CAMPOS OU REGISTROS = SÃO ATRIBUTOS */

CLIENTE 

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - É FEITA PELO AD ADM DE DADOS */ 

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - É FEITA PELO DBA E TAMBÉM PELO AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO 

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO UM BANDO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO DE DADOS*/

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* Sintaxe básica de inserção - INSERT INTO NOME DA TABELA */

/* FORMA 1 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES ('STEPHANIE','F','STEPHANIE.CASTRO@GMAIL.COM',478378102,'959045274','MINISTRO ANIBAL
FREIRE - SÃO PAULO - SP');

INSERT INTO CLIENTE VALUES ('CELIA', 'F', 'CELIA@GMAIL.COM', 541521456, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO
- RJ');

INSERT INTO CLIENTE VALUES ('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');


/* FORMA 2 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO
- RJ','947785696',887774856);


/* FORMA 3 - INSERT COMPACTO - SOMENTE NO MYSQL */

/* ESSE MÉTODO NÃO FUNCIONOU - REFAZER */
INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO 
SÃO PAULO - SP'),
		('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG'); 
		
INSERT INTO CLIENTE VALUES('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');


/* COMANDO SELECT 
seleção - projeção - junção
*/

SELECT NOW();

SELECT NOW() as DATA_HORA;

SELECT 'STEPHANIE CASTRO';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS - TRAZENDO DADOS DE TABELA */

SELECT NOME,SEXO,EMAIL FROM CLIENTE;

SELECT NOME,SEXO,EMAIL,ENDERECO FROM CLIENTE;

SELECT EMAIL,SEXO,ENDERECO,NOME FROM CLIENTE;

SELECT NOME,SEXO,CPF FROM CLIENTE;

SELECT NOME,SEXO,EMAIL, NOW() AS DATA_HORA FROM CLIENTE;

/* PROJETANDO UM ALIAS PARA A COLUNA NOME */

SELECT NOME as CLIENTE,SEXO,EMAIL FROM CLIENTE;

/* SÓ USAR PARA FINS ACADEMICOS - NÃO USE NA EMPRESA */

SELECT * FROM CLIENTE; 

/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE;

/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

/* UTILIZANDO O LIKE PARA PESQUISAR ALGUMA COISA DENTRO DE UM CAMPO */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE 'OSCAR CURY%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';