/* FAZENDO UM UPDATE, INSERT E DELETE EM UMA VIEW (DML) */

INSERT INTO V_RELATORIO VALUES('ANDREIA', 'F', 'ANDREIA@UOL.COM.BR', 'CEL', '478964415', 'CENTRO',
'VITORIA', 'ES');

/* ERRO AO TENTAR FAZER INSERT NA VIEW*/
ERROR 1394 (HY000): Can not insert into join view 'comercio.v_relatorio' without fields list
/* NÃO PODE FAZER INSERT, DELETE EM VIEW DE JOIN */

/* É PERMITIDO FAZER UPDATE EM VIEWS COM JOIN */
UPDATE V_RELATORIO SET NOME = 'JOSE' WHERE NOME = 'JORGE';

CREATE TABLE JOGADORES(
	IDJOGADOR INT,
	NOME VARCHAR(30),
	ESTADO CHAR(2)
);

INSERT INTO JOGADORES VALUES(1, 'GUERREIRO', 'RS');
INSERT INTO JOGADORES VALUES(2, 'ROGER GUEDES', 'SP');
INSERT INTO JOGADORES VALUES(3, 'WILLIAN', 'SP');
INSERT INTO JOGADORES VALUES(4, 'RENATO AUGUSTO', 'SP');
INSERT INTO JOGADORES VALUES(5, 'GABIGOL', 'RJ');

CREATE VIEW V_JOGADORES AS
SELECT NOME, ESTADO
FROM JOGADORES;

SELECT * FROM V_JOGADORES; 

/* FAZENDO UM DELETE EM UMA VIEW SEM JOIN */

DELETE FROM V_JOGADORES
WHERE NOME = 'GUERREIRO';

/* FAZENDO UM INSERT EM UMA VIEW SEM JOIN */

INSERT INTO V_JOGADORES VALUES('GUERREIRO', 'RS');

/* SELEÇÃO */

SELECT * FROM V_RELATORIO
WHERE SEXO = 'F';