/* ESTUDOS - CARDINALIDADE */

--- NOT NULL - O REGISTRO NÃO PODE SER IGNORADO, ELE NÃO PODE DEIXAR DE SER PREENCHIDO
--- ENUM - É UM DOMINIO, PODEMOS DEFINIR E O USUARIO NÃO PODE COLOCAR NADA AO CONTRARIO DO QUE FOI 
--- COLOCADO -  ISSO SÓ EXISTE NO MYSQL
--- UNIQUE - SÓ PODE ENTRAR VALOR UNICO, NÃO ACEITA VALOR DUPLICADO

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL,
	EMAIL VARCHAR(100) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);


INSERT INTO CLIENTE VALUES(NULL, 'JOÃO', 'M', 'JOAO@IG.COM', '789615423');
INSERT INTO CLIENTE VALUES(NULL, 'MARIA', 'F', 'MARIA@IG.COM', '5964125312');
INSERT INTO CLIENTE VALUES(NULL, 'CARLOS', 'M', 'CARLOS@GMAIL.COM', '6423759310');
INSERT INTO CLIENTE VALUES(NULL, 'CLARA', 'F', 'CLARA@HOTMAIL.COM', '3134796423');
INSERT INTO CLIENTE VALUES(NULL, 'MANUELA', 'F', NULL, '4593107985');
INSERT INTO CLIENTE VALUES(NULL, 'ANA', 'F', 'ANA@UOL.COM', '8976387520');
INSERT INTO CLIENTE VALUES(NULL, 'MARCOS', 'M', 'MARCOS@IG.COM', '6478945120');
INSERT INTO CLIENTE VALUES(NULL, 'RICARDO', 'M', 'RICARDO@GLOBO.COM', '4579878952');
INSERT INTO CLIENTE VALUES(NULL, 'KAREN', 'F', NULL, NULL);
INSERT INTO CLIENTE VALUES(NULL, 'JORGE', 'M', 'JORGE@OUTLOOK.COM', '3456978452');

SELECT * FROM CLIENTE;


INSERT INTO ENDERECO VALUES(NULL, 'RUA ANTONIO SA', 'CENTRO', 'BELO HORIZONTE', 'MG', 4);
INSERT INTO ENDERECO VALUES(NULL, 'RUA MINISTRO ANIBAL', 'JARAGUA', 'SÃO PAULO', 'SP', 2);
INSERT INTO ENDERECO VALUES(NULL, 'RUA OUVIDOR', 'CENTRO', 'RIO DE JANEIRO', 'RJ', 1);
INSERT INTO ENDERECO VALUES(NULL, 'RUA PRES VARGAS', 'JARDINS', 'SÃO PAULO', 'SP', 3);
INSERT INTO ENDERECO VALUES(NULL, 'RUA VOLUNTARIOS', 'SANTANA', 'SÃO PAULO', 'SP', 5);
INSERT INTO ENDERECO VALUES(NULL, 'RUA JORGE JESUS', 'FONTALIS', 'RIO GRANDE DO SUL', 'RS',7);
INSERT INTO ENDERECO VALUES(NULL, 'AVENIDA CASTOR', 'JARAU', 'PARANÁ', 'PR',6);
INSERT INTO ENDERECO VALUES(NULL, 'RECANTO ALEGRE', 'MARIA MARCOLINA', 'PARÁ', 'PA', 8);
INSERT INTO ENDERECO VALUES(NULL, 'RUA URUGUAIANA', 'FLAMENGO', 'RIO DE JANEIRO', 'RJ',10);
INSERT INTO ENDERECO VALUES(NULL, 'RUA CAPITAO HERMES', 'CENTRO', 'SANTA CATARINA', 'SC', 9);

SELECT * FROM ENDERECO;


INSERT INTO TELEFONE VALUES(NULL, 'CEL', '98875642', 5);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '34794289', 5);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '34597963', 6);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '66978940', 1);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '79845139', 2);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '36978496', 10);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '34679856', 8);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '88946230', 7);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '66978452', 4);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '34978962', 3);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '88975813', 3);

SELECT * FROM TELEFONE;


DROP TABLE TELEFONE;
DROP TABLE ENDERECO;