/* EXERCICIO DE DML - MANIPULAÇÃO DE DADOS */

/* INSERINDO OS DADOS DA MINHA TABELA */

INSERT INTO CLIENTE VALUES(NULL, 'VIRGINIA', 'F', 'VIRGINIA@BOL.COM.BR', '20930248509');
INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');

/* CADASTRE UM ENDERECO PARA CADA CLIENTE */

INSERT INTO ENDERECO VALUES(NULL,'RUA SÃO JOSÉ','PERY', 'SÃO PAULO','SP',25);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',13);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',14);
INSERT INTO ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',15);
INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',18);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',16);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',19);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',20);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',26);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',21);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',22);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',17);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',23);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',24);


/* CADASTRE TELEFONES PARA OS CLIENTES */

INSERT INTO TELEFONE VALUES(NULL,'CEL','65787654',13);
INSERT INTO TELEFONE VALUES(NULL,'RES','68976565',14);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',13);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',15);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',16);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',17);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',18);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',13);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',15);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',25);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',23);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',22);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',21);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',26);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',18);


/* RELATORIO GERAL DE TODOS OS CLIENTES */

SELECT CLIENTE.IDCLIENTE, CLIENTE.NOME, CLIENTE.SEXO, CLIENTE.EMAIL, CLIENTE.CPF,
	   TELEFONE.TIPO, TELEFONE.NUMERO,
	   ENDERECO.RUA, ENDERECO.CIDADE, ENDERECO.ESTADO
FROM CLIENTE 
INNER JOIN TELEFONE
	ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
INNER JOIN ENDERECO
	ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE;



/* RELATORIO DE HOMENS */

SELECT CLIENTE.IDCLIENTE, CLIENTE.NOME, CLIENTE.SEXO, CLIENTE.EMAIL, CLIENTE.CPF,
	   TELEFONE.TIPO, TELEFONE.NUMERO,
	   ENDERECO.RUA, ENDERECO.CIDADE, ENDERECO.ESTADO
FROM CLIENTE 
INNER JOIN TELEFONE
	ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
INNER JOIN ENDERECO
	ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
WHERE SEXO = 'M';



/* UPDATE DOS IDS - 17, 18, 19, 23*/

UPDATE CLIENTE 
SET SEXO = 'F'
WHERE IDCLIENTE = 17;

UPDATE CLIENTE 
SET SEXO = 'F'
WHERE IDCLIENTE = 18;

UPDATE CLIENTE 
SET SEXO = 'F'
WHERE IDCLIENTE IN (19, 23);

/* RELATORIO DE MULHERES */

SELECT CLIENTE.IDCLIENTE, CLIENTE.NOME, CLIENTE.SEXO, CLIENTE.EMAIL, CLIENTE.CPF,
	   TELEFONE.TIPO, TELEFONE.NUMERO,
	   ENDERECO.RUA, ENDERECO.CIDADE, ENDERECO.ESTADO
FROM CLIENTE 
INNER JOIN TELEFONE
 	ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
 INNER JOIN ENDERECO
 	ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
 WHERE SEXO = 'F';

UPDATE CLIENTE 
SET SEXO  = 'M'
WHERE IDCLIENTE  = '21';



/* QUANTIDADE DE HOMENS E MULHERES */

SELECT COUNT(*) AS QUANTIDADE, SEXO
FROM CLIENTE 
GROUP BY SEXO;



/* IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E NÃO TENHAM CELULAR */

SELECT CLIENTE.IDCLIENTE, CLIENTE.EMAIL, CLIENTE.NOME, CLIENTE.SEXO,
	   ENDERECO.BAIRRO, ENDERECO.CIDADE,
	   TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO
	ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
	ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE 
WHERE SEXO = 'F' 
AND BAIRRO = 'CENTRO'
AND CIDADE = 'RIO DE JANEIRO'
AND (TIPO = 'RES' OR TIPO = 'COM');


/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM RELATÓRIO COM O NOME, EMAIL 
E TELEFONE CELULAR DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO, VOCÊ TERÁ
QUE PASSSAR A QUERY PARA GERAR UM RELATÓRIO PARA O PROGRAMADOR */

SELECT CLIENTE.NOME, CLIENTE.EMAIL,
	   TELEFONE.NUMERO AS CELULAR,
	   ENDERECO.ESTADO
FROM CLIENTE 
INNER JOIN TELEFONE
	ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
INNER JOIN ENDERECO
	ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
WHERE TIPO = 'CEL'
AND ESTADO = 'RJ';


/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM RELATÓRIO COM NOME,
EMAIL E TELEFONE CELULAR DAS MULHERES QUE MORAM EM SÃO PAULO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATÓRIO PARA O PROGRAMADOR */

SELECT CLIENTE.NOME, CLIENTE.EMAIL,
	   TELEFONE.NUMERO AS CELULAR,
	   ENDERECO.ESTADO
FROM CLIENTE 
INNER JOIN TELEFONE 
	ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
INNER JOIN ENDERECO 
	ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
WHERE TIPO = 'CEL'
AND ESTADO = 'SP';		

