/* FILTRANDO VALORES NULOS */

/* VENDO AS TABELAS QUE TENHO NO MEU BANCO DE DADOS */
SHOW DATABASES;

/* ME CONECTANDO AO BANCO */
USE PROJETO;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

/* PESQUISANDO TODOS OS EMAILS COM VALORES NULOS */
/* NUNCA UTILIZE O SINAL DE = PARA FILTRAR VALORES NULOS. ISSO PORQUE NÃO SABEMOS O QUE UM VALOR NULL É */
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE EMAIL IS NULL;

/* PESQUISANDO TODOS QUE NÃO TEM EMAIL NULL */
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE EMAIL IS NOT NULL;

