/* EXERCOCIO 1 LIVRARIA */

/* CRIANDO OS ATRIBUTOS */

LIVRARIA

NOMELIVRO - CARACTER(100)
NOMEAUTOR - CARACTER(100)
SEXOAUTOR - VARCHAR(1)
NUMEROPAGINAS - INTEIRO(5)
NOMEEDITORA - CATACTER(30)
VALORLIVRO - FLOAT(6)
ESTADOEDITORA - VARCHAR(2)
ANOPUBLICACAO - VARCHAR(4)

/* JA CRIEI MINHA MODELAGEM DE DADOS NO BR MODELO */

/* CRIANDO MEU PROJETO */

CREATE DATABASE LIVRARIA;

/* ME CONECTANDO AO BANDO DE DADOS */

USE LIVRARIA;

/* CRIANDO A MINHA TABELA DA LIVRARIA */

CREATE TABLE LIVROS(
	LIVRO VARCHAR(100),
	AUTOR VARCHAR(100),
	SEXO CHAR(1),
	PAGINAS INT(5),
	EDITORA VARCHAR(30),
	VALOR FLOAT(10,2),
	ESTADO CHAR(2),
	PUBLICACAO INT(4)
);	

/* VERIFICANDO A MINHA TABELA NO BANCO DE DADOS */

SHOW TABLES;

/* VERIFICANDO TODAS AS TABELAS JA CRIADAS NO MEU BANCO */

SHOW DATABASES;

/* COMO SABER EM QUAL DATABASE ESTOU CONECTADA */

STATUS;

/* VERIFICANDO A DESCRIÇÃO DA MINHA TABELA*/

DESC LIVROS;

/* INSERINDO DADOS - NÃO OMITINDO AS COLUNAS */

INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO, PUBLICACAO)
VALUES('CAVALEIRO REAL', 'ANA CLAUDIA', 'F', 465, 'ATLAS', 49.9, 'RJ', 2009);

INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO, PUBLICACAO)
VALUES('SQL PARA LEIGOS', 'JOÃO NUNES', 'M', 450, 'ADDISON', 98, 'SP', 2018);

INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO, PUBLICACAO)
VALUES('RECEITAS CASEIRAS', 'CELIA TAVARES', 'F', 210, 'ATLAS', 45, 'RJ', 2008);

INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO, PUBLICACAO)
VALUES('PESSOAS EFETIVAS', 'EDUARDO SANTOS', 'M', 390, 'BETA', 78.99, 'RJ', 2018);

INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO, PUBLICACAO)
VALUES('A CASA MARROM', 'HERMES MACEDO', 'M', 250, 'BUBBA', 60, 'MG', 2016);

INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO, PUBLICACAO)
VALUES('ESTACIO QUERIDO', 'GERALDO FRANCISCO', 'M', 310, 'INSIGNIA', 100, 'ES', 2015);

INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO, PUBLICACAO)
VALUES('PRA SEMPRE AMIGAS', 'LEDA SILVA', 'F', 510, 'INSIGNIA', 78.98, 'ES', 2011);

INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO, PUBLICACAO)
VALUES('COPAS INESQUECIVEIS', 'MARCO ALCANTARA', 'M', 200, 'LARSON', 130.98, 'RS', 2018);

INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO, PUBLICACAO)
VALUES('O PODER DA MENTE', 'CLARA MAFRA', 'F', 120, 'CONTINENTAL', 56.58, 'SP', 2017); 

/* INSERINDO DADOS OMITINDO AS COLUNAS */

INSERT INTO LIVROS VALUES('CAVALEIRO REAL', 'ANA CLAUDIA', 'F', 465, 'ATLAS', 49.9, 'RJ', 2009);
INSERT INTO LIVROS VALUES('SQL PARA LEIGOS', 'JOÃO NUNES', 'M', 450, 'ADDISON', 98, 'SP', 2018);
INSERT INTO LIVROS VALUES('RECEITAS CASEIRAS', 'CELIA TAVARES', 'F', 210, 'ATLAS', 45, 'RJ', 2008);
INSERT INTO LIVROS VALUES('PESSOAS EFETIVAS', 'EDUARDO SANTOS', 'M', 390, 'BETA', 78.99, 'RJ', 2018);
INSERT INTO LIVROS VALUES('A CASA MARROM', 'HERMES MACEDO', 'M', 250, 'BUBBA', 60, 'MG', 2016);
INSERT INTO LIVROS VALUES('ESTACIO QUERIDO', 'GERALDO FRANCISCO', 'M', 310, 'INSIGNIA', 100, 'ES', 2015);
INSERT INTO LIVROS VALUES('PRA SEMPRE AMIGAS', 'LEDA SILVA', 'F', 510, 'INSIGNIA', 78.98, 'ES', 2011);
INSERT INTO LIVROS VALUES('COPAS INESQUECIVEIS', 'MARCO ALCANTARA', 'M', 200, 'LARSON', 130.98, 'RS', 2018);
INSERT INTO LIVROS VALUES('O PODER DA MENTE', 'CLARA MAFRA', 'F', 120, 'CONTINENTAL', 56.58, 'SP', 2017); 

/* ESPECIFICAÇÕES DO ESCOPO */

/*TRAZER TODOS OS DADOS DA TABELA*/

SELECT * FROM LIVROS;

/* TRAZER O NOME DO LIVRO E O NOME DA EDITORA */

SELECT LIVRO, EDITORA FROM LIVROS;

/* TRAZER O NOME DO LIVRO E DO UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO */

SELECT LIVRO, ESTADO FROM LIVROS
WHERE SEXO = 'M';

/* TRAZER O NOME DO LIVRO E O NUMERO DE PAG DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO*/

SELECT LIVRO, PAGINAS FROM LIVROS
WHERE SEXO = 'F';

/* TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SP */

SELECT VALOR FROM LIVROS
WHERE ESTADO = 'SP';

/* TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SP OU RJ */

SELECT AUTOR, SEXO FROM LIVROS
WHERE SEXO = 'M' 
AND ESTADO = 'SP'
OR ESTADO = 'RJ';