/* FAZENDO A MODELAGEM BÁSICO DE UM BANCO */

TABELA TESTE

NOME - CARACTER(30)
IDADE - NUMERICO(3)
SEXO - CARACTER(1)
TELEFONE - CARACTER(30)
PROFISSAO - CARACTER(100)

/* CRIANDO A MODEGALEM NO BR MODELO */

MODELAGEM LÓGICA 

/* CRIANDO A MODELAGEM FISICA - SCRIPTS DE BANCO DE DADOS */

/* CRIANDO UM BANCO DE DADOS */

CREATE DATABASE TESTE;

/* ME CONECTANDO AO BANDO DE DADOS */

USE TESTE;

/* CRIANDO A TABELA TESTE */

CREATE TABLE TESTE(
	NOME VARCHAR(30),
	IDADE INT(3),
	SEXO CHAR(1),
	TELEFONE VARCHAR(30),
	PROFISSAO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO DE DADOS */

SHOW TABLES;

/* VERIFICANDO A ESTRUTURA DA MINHA TABELA */

DESC TESTE;