/* UTILIZANDO O UPDATE */

/* UPDATE ATUALIZA OS REGISTROS QUE JA ESTÃO NA TABELA */

/* UTILIZANDO O UPDATE PARA ATUALIZAR VALORES */

SELECT NOME, EMAIL FROM CLIENTE;

/* UTILIZANDO ESSE METODO ATUALIZA TODOS OS EMAILS */

UPDATE CLIENTE 
SET EMAIL = 'LILIAN@HOTMAIL.COM';

SELECT * FROM CLIENTE
WHERE NOME = 'LILIAN';

/*FAZENDO O UPDATE DA FORMA CORRETA USANDO O WHERE PARA FAZER A SELEÇÃO DO VALOR QUE EU QUERO ATUALIZAR - É IMPORTANTE SEMPRE 
USAR O WHERE JUNTO COM O UPDATE PARA ATUALIZAR APENAS O REGISTRO SELECINADO */
UPDATE CLIENTE
SET EMAIL = 'JORGE@IG.COM.BR'
WHERE NOME = 'JORGE';

UPDATE CLIENTE
SET EMAIL = 'CELIA@GMAIL.COM.BR'
WHERE NOME = 'CELIA';

UPDATE CLIENTE
SET EMAIL = 'STEPHANIE@GMAIL.COM'
WHERE NOME = 'STEPHANIE';

UPDATE CLIENTE
SET EMAIL = 'ANA@OUTLOOK.COM'
WHERE NOME = 'ANA';

UPDATE CLIENTE
SET EMAIL = 'CARLA@HOTMAIL.COM'
WHERE NOME = 'CARLA';

UPDATE CLIENTE
SET ENDERECO = 'JARAGUA - ZONA OESTE - SÃO PAULO - SP'
WHERE NOME = 'STEPHANIE';

UPDATE CLIENTE
SET ENDERECO = 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ'
WHERE NOME = 'CELIA';

UPDATE CLIENTE 
SET ENDERECO = 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ'
WHERE NOME = 'LILIAN';

UPDATE CLIENTE
SET ENDERECO = 'PRES ANTONIO CARLOS - CENTRO - SÃO PAULO - SP'
WHERE NOME = 'ANA';


